"""empty message

Revision ID: 776ace608512
Revises: 6fb8d7472c3f
Create Date: 2024-05-28 14:42:58.591278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776ace608512'
down_revision = '6fb8d7472c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowing_history', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('borrower_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('unique_email', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), nullable=False))
        batch_op.create_unique_constraint('unique_email', ['email'])

    with op.batch_alter_table('borrowing_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
